from typing import Optional, Union

class Device: ...

class ThreadDevice(Device):
    def __init__(
        self,
        device_type: int = ...,
        in_type: Optional[int] = ...,
        out_type: Optional[int] = ...,
    ) -> None: ...
    def bind_in(self, addr: str) -> None: ...
    def bind_out(self, addr: str) -> None: ...
    def start(self) -> None: ...
    def join(self, timeout: Optional[float] = ...) -> None: ...
    def setsockopt_in(self, opt: int, value: Union[int, bytes]) -> None: ...
