#!/bin/bash -e

info="\033[1;36m"
success="\033[1;32m"
clear="\033[0m"

if [ ! -z "$(git diff --name-only HEAD dawn | head -1)" ]; then
  echo -e "${info}:: Checking Dawn ...${clear}"
  pushd dawn &>/dev/null
  npm install --quiet --also=dev
  npm run --silent format:check
  npm run --silent lint
  popd &>/dev/null
fi

if [ ! -z "$(git diff --name-only HEAD shepherd | head -1)" ]; then
  echo -e "${info}:: Checking Shepherd ...${clear}"
  pushd shepherd  &>/dev/null
  npm install --quiet --also=dev
  npm run --silent format:check
  npm run --silent lint
  popd  &>/dev/null
fi

if [ ! -z "$(git diff --name-only HEAD runtime | head -1)" ]; then
  echo -e "${info}:: Checking Runtime ...${clear}"
  pushd runtime  &>/dev/null
  pipenv run format:check
  pipenv run lint
  pipenv run typecheck
  popd  &>/dev/null
fi

echo -e "${success}All projects passed static checks!${clear}"
