env:
  browser: true
  es2021: true
  node: true
extends:
  - semistandard
  - 'plugin:react/recommended'
  - 'plugin:promise/recommended'
  - 'plugin:jest/recommended'
  - prettier
ignorePatterns:
  - /build
  - /coverage
  - /dist
  - /node_modules
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - promise
  - jest
  - '@typescript-eslint'
rules:
  comma-dangle:
    - error
    - only-multiline
  no-use-before-define: off
  no-unused-vars: off
  '@typescript-eslint/no-unused-vars': error
settings:
  react:
    version: detect
