env:
  browser: true
  es2021: true
  node: true
extends:
  - semistandard
  - 'plugin:react/recommended'
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  comma-dangle: ['error', 'only-multiline']
  no-use-before-define: off
  '@typescript-eslint/no-use-before-define': error
  no-unused-vars: off
  '@typescript-eslint/no-unused-vars': error
settings:
  react:
    version: detect
